# Generated by Django 5.2.17 on 2026-09-10 05:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profissionais", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("data_hora", models.DateTimeField(db_index=True, verbose_name="Data e Hora")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendada", "Agendada"),
                            ("confirmada", "Confirmada"),
                            ("realizada", "Realizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="agendada",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("observacoes", models.TextField(blank=True, default="", verbose_name="Observações")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultas",
                        to="profissionais.profissional",
                        verbose_name="Profissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "ordering": ["-data_hora"],
                "indexes": [
                    models.Index(fields=["profissional", "-data_hora"], name="idx_cons_prof_data"),
                    models.Index(fields=["status", "-data_hora"], name="idx_cons_status_data"),
                ],
            },
        ),
    ]
