# Generated by Django 5.2.17 on 2026-09-10 05:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profissional",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nome_social", models.CharField(max_length=255, verbose_name="Nome Social")),
                ("profissao", models.CharField(max_length=100, verbose_name="Profissão")),
                ("endereco", models.CharField(max_length=500, verbose_name="Endereço")),
                ("contato_telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("contato_email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("ativo", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Criado em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Profissional",
                "verbose_name_plural": "Profissionais",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(fields=["ativo", "-criado_em"], name="idx_prof_ativo_criado"),
                    models.Index(fields=["nome_social"], name="idx_prof_nome_social"),
                ],
            },
        ),
    ]
